# ---------------------------------------------------------------------
# Gufo Ping: _fast stub
# This is a stub file for pyo3 module only to satisfy
# the mkdocstings
# ---------------------------------------------------------------------
# Copyright (C) 2022-26, Gufo Labs
# ---------------------------------------------------------------------

# Python modules
from typing import Dict, Optional

class SocketWrapper(object):
    def __init__(self, afi: int) -> None: ...
    def set_timeout(self, timeout: int) -> None: ...
    def bind(self, addr: str) -> None: ...
    def set_ttl(self, ttl: int) -> None: ...
    def set_unicast_hops(self, ttl: int) -> None: ...
    def set_tos(self, tos: int) -> None: ...
    def set_tclass(self, tos: int) -> None: ...
    def set_send_buffer_size(self, size: int) -> None: ...
    def set_recv_buffer_size(self, size: int) -> None: ...
    def set_coarse(self, coarse: bool) -> None: ...
    def get_fd(self) -> int: ...
    def send(
        self, addr: str, request_id: int, seq: int, size: int
    ) -> None: ...
    def recv(self) -> Optional[Dict[str, int]]: ...
