# ---------------------------------------------------------------------
# Gufo Ping: _fast stub
# This is a stub file for pyo3 module only to satisfy
# the mkdocstings
# ---------------------------------------------------------------------
# Copyright (C) 2022-26, Gufo Labs
# ---------------------------------------------------------------------

PS_DGRAM: int
PS_DGRAM_RAW: int
PS_IPV4: int
PS_IPV6: int
PS_RAW: int
PS_RAW_DGRAM: int

class SocketWrapper(object):
    def __init__(self, policy: int, timeout_ns: int, coarse: bool) -> None: ...
    def bind(self, addr: str) -> None: ...
    def set_ttl(self, ttl: int) -> None: ...
    def set_unicast_hops(self, ttl: int) -> None: ...
    def set_tos(self, tos: int) -> None: ...
    def set_tclass(self, tos: int) -> None: ...
    def set_send_buffer_size(self, size: int) -> None: ...
    def set_recv_buffer_size(self, size: int) -> None: ...
    def get_fd(self) -> int: ...
    def send(self, addr: str, size: int) -> None: ...
    def recv(self) -> dict[str, int] | None: ...
