name: Build Docs
env:
  PIP_CACHE_DIR: .pip
  PYTHONPATH: src
on:
  push:
    paths:
      - ".github/workflows/build-docs.yml"
      - "docs/**"
      - "examples/**"
      - "src/**"
      - "*.md"
      - "pyproject.toml"
    branches:
      - master
jobs:
  build-push:
    name: "Build & Push Docs"
    runs-on: ubuntu-24.04
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      # Cache dependencies
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ./.pip
          key: ${{ runner.os }}-docs-${{ hashFiles('pyproject.toml') }}

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install -IU -e .[docs]

      # Build documentationn
      - name: Build & Deploy Docs
        run: |
          mkdocs gh-deploy --strict --force
